In [1]:
import numpy as np

In [2]:
x = np.array([1, 4, 3])
x

array([1, 4, 3])

In [3]:
y = np.array([[1, 4, 3], [9, 2, 7]])
y

array([[1, 4, 3],
       [9, 2, 7]])

In [4]:
y.shape

(2, 3)

In [5]:
y.size

6

In [6]:
z = np.arange(1, 2000, 1)
z

array([   1,    2,    3, ..., 1997, 1998, 1999])

In [7]:
np.arange(0.5, 3, 0.5)

array([0.5, 1. , 1.5, 2. , 2.5])

In [8]:
np.linspace(3, 9, 10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

In [9]:
# get the 2nd element of x
x[1]

4

In [10]:
# get all the element after the 2nd element of x
x[1:]

array([4, 3])

In [11]:
# get the last element of x
x[-1]

3

In [12]:
y[0,1]

4

In [13]:
y[0, :]

array([1, 4, 3])

In [14]:
y[:, -1]

array([3, 7])

In [15]:
y[:, [0, 2]]

array([[1, 3],
       [9, 7]])

In [16]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.empty(3)

array([4.24399158e-314, 4.23762559e-311, 4.24186959e-311])

In [19]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [20]:
a[3] = 7
a

array([1, 2, 3, 7, 5, 6])

In [21]:
a[:3] = 1
a

array([1, 1, 1, 7, 5, 6])

In [22]:
a[1:4] = [9, 8, 7]
a

array([1, 9, 8, 7, 5, 6])

In [23]:
b = np.zeros((2, 2))
b[0, 0] = 1
b[0, 1] = 2
b[1, 0] = 3
b[1, 1] = 4
b

array([[1., 2.],
       [3., 4.]])

In [24]:
b + 2

array([[3., 4.],
       [5., 6.]])

In [25]:
b - 2

array([[-1.,  0.],
       [ 1.,  2.]])

In [26]:
2 * b

array([[2., 4.],
       [6., 8.]])

In [27]:
b / 2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [28]:
b**2

array([[ 1.,  4.],
       [ 9., 16.]])

In [29]:
b = np.array([[1, 2], [3, 4]])
d = np.array([[3, 4], [5, 6]])

In [30]:
b + d

array([[ 4,  6],
       [ 8, 10]])

In [31]:
b - d

array([[-2, -2],
       [-2, -2]])

In [32]:
b * d

array([[ 3,  8],
       [15, 24]])

In [33]:
b / d

array([[0.33333333, 0.5       ],
       [0.6       , 0.66666667]])

In [34]:
b**d

array([[   1,   16],
       [ 243, 4096]], dtype=int32)

In [35]:
b.T

array([[1, 3],
       [2, 4]])

In [36]:
x = [1, 4, 9, 16]
np.sqrt(x)

array([1., 2., 3., 4.])

In [37]:
x = np.array([1, 2, 4, 5, 9, 3])
y = np.array([0, 2, 3, 1, 2, 3])

In [38]:
x > 3

array([False, False,  True,  True,  True, False])

In [39]:
x > y

array([ True, False,  True,  True,  True, False])

In [40]:
y = x[x > 3]
y

array([4, 5, 9])

In [41]:
x[x > 3] = 0
x

array([1, 2, 0, 0, 0, 3])